pipeline {
    agent any
    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "Maven"
    }
    
    stages {
        stage('Checkout') {
            steps {
                // Clonar el repositorio Git
                git url: 'https://github.com/MiguelLopezDeVicente/GPI2.git', branch: 'main'
            }
        }
        stage('Test') {
            steps {
              dir('kernel') {
                sh 'mvn test'
                }
            }
        }
    }
}
